name: Pull request check for webapp repo
on:
  pull_request:
    types: 
      - opened
    branches:
      - main
jobs:
  build_test_java_app:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # - name: Check Secrets
      #   run: |
      #     if [ -z "${{ secrets.DB_URL }}" ]; then echo "DB_URL isnt set"; else echo "DB_URL is set"; fi
      #     if [ -z "${{ secrets.DB_USERNAME }}" ]; then echo "DB_USERNAME is not set"; else echo "DB_USERNAME is set"; fi
      #     if [ -z "${{ secrets.DB_PASSWORD }}" ]; then echo "DB_PASSWORD is not set"; else echo "DB_PASSWORD is set"; fi
        

      - name: Run with Maven
        working-directory: ./CloudDemo_CSYE_6225
        run: mvn clean install
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.DB_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}

  packer_pr_check:
    defaults:
      run:
        working-directory: ./packer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Packer
        uses: hashicorp/setup-packer@v3

      - name: Init Packer
        run: packer init .

      - name: Packer fmt check
        run: packer fmt -check -recursive .

      - name: Validate Packer template
        run: packer validate .